name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # رجعنا لـ Java 11 حيت Gradle 6.5 ما كايقبلش Java 17
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # بناء الـ APK
    - name: Build Debug APK
      run: ./gradlew assembleDebug

    # استخراج الـ APK
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Android-App-Debug
        path: app/build/outputs/apk/debug/*.apk
